[package]
name = "poem_example"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { version = "3.1.12", features = ["tower"] }
poem_auth = { path = "../..", features = ["sqlite"] }
tokio = { version = "1.49.0", features = ["full"] }
serde_json = "1"
